# Generated by Django 4.0.2 on 2022-03-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborName', models.CharField(max_length=45)),
                ('neighborType', models.CharField(max_length=45)),
                ('neighborBirthDay', models.DateTimeField()),
                ('neighborAdded', models.DateTimeField(auto_now_add=True)),
                ('neighborUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
